const Ticket=[
    {
        id:1,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"0",
        Infants :"0",
        cabin:"Economy"
    },
    {
        id:2,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"1",
        Infants :"0",
        cabin:"Economy"
    },
    {
        id:3,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "3",
        Childen :"2",
        Infants :"0",
        cabin:"Economy"
    },
    {
        id:4,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"1",
        Infants :"1",
        cabin:"Economy"
    },
    {
        id:5,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"1",
        cabin:"Economy"
    },
    {
        id:6,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"2",
        cabin:"Economy"
    },
    {
        id:7,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"0",
        Infants :"0",
        cabin:"Premium Economy"
    },
    {
        id:8,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"1",
        Infants :"0",
        cabin:"Premium Economy"
    },
    {
        id:9,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "3",
        Childen :"2",
        Infants :"0",
        cabin:"Premium Economy"
    },
    {
        id:10,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"1",
        Infants :"1",
        cabin:"Premium Economy"
    },
    {
        id:11,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"1",
        cabin:"Premium Economy"
    },
    {
        id:12,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"2",
        cabin:"Premium Economy"
    },
    {
        id:13,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"0",
        Infants :"0",
        cabin:"Business"
    },
    {
        id:14,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"1",
        Infants :"0",
        cabin:"Business"
    },
    {
        id:15,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "3",
        Childen :"2",
        Infants :"0",
        cabin:"Business"
    },
    {
        id:16,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"1",
        Infants :"1",
        cabin:"Business"
    },
    {
        id:17,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"1",
        cabin:"Business"
    },
    {
        id:18,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"2",
        cabin:"Business"
    },
    {
        id:19,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"2",
        cabin:"First"
    },
    {
        id:20,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"0",
        Infants :"0",
        cabin:"First"
    },
    {
        id:21,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"1",
        Infants :"0",
        cabin:"First"
    },
    {
        id:22,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "3",
        Childen :"2",
        Infants :"0",
        cabin:"First"
    },
    {
        id:23,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "1",
        Childen :"1",
        Infants :"1",
        cabin:"First"
    },
    {
        id:24,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"1",
        cabin:"First"
    },
    {
        id:25,
        From:"chennai",
        To:"Goa",
        Depart :"28/07/2023",
        Return : "30/07/2023",
        Adults : "2",
        Childen :"2",
        Infants :"2",
        cabin:"First"
    },

]
export default Ticket;